### ISSUE TITLE
Disable HMM feature of Jieba

### ISSUE THREAD

**Issue by ManyTheFish** [meilisearch/charabia#136]
Today, we are using the Hidden Markov Model algorithm (HMM) provided by the [`cut` method](https://docs.rs/jieba-rs/0.6.6/jieba_rs/struct.Jieba.html#method.cut) of Jieba to segment unknown Chinese words in the [Chinese segmenter](https://github.com/meilisearch/charabia/blob/dac6b422e43b666cc232430533e61a50abdd3341/src/segmenter/chinese.rs#L14).

#### drawback
Following [the subdiscussion](https://github.com/meilisearch/product/discussions/503#discussioncomment-3456196) in the official discussion about Chinese support in Meilisearch, it seems that the HMM feature of Jieba is not relevant in the context of a search engine. This feature creates longer words and inconsistencies in the segmentation, which reduces the recall of Meilisearch without significantly raising the precision.

#### enhancement

Deactivate the HMM feature in Chinese segmentation.

#### Files expected to be modified
- [/src/segmenter/chinese.rs](https://github.com/meilisearch/charabia/blob/dac6b422e43b666cc232430533e61a50abdd3341/src/segmenter/chinese.rs)

#### Misc
related to [product#503](https://github.com/meilisearch/product/discussions/503)

> Hey! 👋 
Before starting any implementation, make sure that you read the [CONTRIBUTING.md](https://github.com/meilisearch/charabia/blob/main/CONTRIBUTING.md#contributing) file.
In addition to the recurrent rules, you can find some guides to easily implement a `Segmenter` or a `Normalizer`.
Thanks a lot for your Contribution! 🤝

**Comment by aniketh-varma** [comment]
Hi @ManyTheFish, I would like to work on this issue.

**Comment by irevoire** [comment]
Hello @aniketh-varma,

Thanks for your interest in this project 🔥 You are definitely more than welcome to open a PR for this!
Our contributing guidelines are available [here](../blob/main/CONTRIBUTING.md) and will guide you through your contribution. If you have any questions, you can also ask them here!

FYI, we prefer not assigning people to our issues because sometimes people ask to be assigned and never come back, which discourages the volunteer contributors from opening a PR to fix this issue.
We will accept and merge the first PR that fixes correctly and well implements the issue following our [contributing guidelines](../blob/main/CONTRIBUTING.md).   

We are looking forward to reviewing your PR 😊
