### ISSUE TITLE
Upgrade Whatlang dependency

### ISSUE THREAD

**Issue by ManyTheFish** [meilisearch/charabia#141]
Whatlang introduced new Languages and Scripts in the newer version.
We should upgrade our dependency to the latest version.

**Comment by Sokom141** [comment]
Hi, can I work on this?

**Comment by curquiza** [comment]
Hello @Sokom141 

Thanks for your interest in this project 🔥 You are definitely more than welcome to open a PR for this!

FYI, we prefer not assigning people to our issues because sometimes people ask to be assigned and never come back, which discourages the volunteer contributors from opening a PR to fix this issue.
We will accept and merge the first PR that fixes correctly and well implements the issue following our [contributing guidelines](../blob/main/CONTRIBUTING.md).   

We are looking forward to reviewing your PR 😊
