### ISSUE TITLE
The `chinese-normalization-pinyin` feature flag doesn't compile

### ISSUE THREAD

**Issue by ManyTheFish** [meilisearch/charabia#290]
## Reproduction

`cargo test --verbose --features chinese-normalization-pinyin`

## Fix

1) Fix the [CI testing the flag](https://github.com/meilisearch/charabia/blob/eb3326d5de494f9cc497c9903520449e7f43033f/.github/workflows/rust.yml#L30) using `cargo test --verbose --features chinese-normalization-pinyin` instead of `cargo test --verbose --features chinese chinese-normalization-pinyin`
1) the CI should not work anymore
1) Fix the compilation issue [in the normalizer](https://github.com/meilisearch/charabia/blob/main/charabia/src/normalizer/chinese.rs)

related to https://github.com/meilisearch/meilisearch/issues/4629

**Comment by Soham1803** [comment]
Just to be clear, what's expected here is the new CI command i.e. `cargo test --verbose --features chinese-normalization-pinyin` instead of the older `cargo test --verbose --features chinese chinese-normalization-pinyin` which currently runs fine. Am I right?
When currently we run `cargo test --verbose --features chinese-normalization-pinyin` total *102+9* tests run whereas we expect only one test related to *chinese normalizer* to run.

**Comment by ManyTheFish** [comment]
I made a mistake when putting `cargo test --verbose --features chinese chinese-normalization-pinyin` because in this case the flag `chinese-normalization-pinyin` is ignored, the proper command to run would be `cargo test --verbose --features chinese,chinese-normalization-pinyin` but because `chinese-normalization-pinyin` force the flag `chinese`, it's not necessary to re-precise it.
That's why `cargo test --verbose --features chinese-normalization-pinyin` is sufficient.
The goal is to ensure that the code under this flag is tested and works. Currently it doesn't.

**Comment by Soham1803** [comment]
Hey @ManyTheFish! Waiting for your review to this above PR by @tkhshtsh0917. I actually doubt whether that's the complete solution. Because even after that if you run `cargo test --verbose --features chinese-normalization-pinyin` it executes all **102+9** tests which is what happens when you simply run **cargo test**. I might be wrong about this. I'm sorry, I'm just curious and want to know more about this project.

**Comment by tkhshtsh0917** [comment]
Hi @Soham1803! I'm trying to understand your thoughts, are you arguing that we should use a trick where only the features specified in `cargo test --features` are tested and other features are skipped?

Like this?
ref: https://stackoverflow.com/questions/77529267/how-to-run-only-tests-marked-with-a-specific-feature-and-ignoring-the-rest

**Comment by ManyTheFish** [comment]
Hello @Soham1803 and @tkhshtsh0917, you are right. The number of tests doesn't change; however, they are not exactly the same. In the [Chinese normalizer tests](https://github.com/meilisearch/charabia/blob/6b270fcae0e43a3cebf62d5c0892a4a3e021276c/charabia/src/normalizer/chinese.rs#L84-L229) the expected result change depending on the feature flag. Whit your PR, both sides will be tested.

**Comment by Soham1803** [comment]
Oh yes! I get it now. Thanks @ManyTheFish for clearing my doubt and all the best @tkhshtsh0917 with your PR. 😊
